Main group 11 requisito 5
tryber/sd-010-b-project-frontend-online-store pull request #164
Opened 2021-05-16 20:43 UTC by Daniel-hash-svg

Requisito 5 Completo.

2021-05-16 20:50 UTC, CIGR2021 approved these changes

2021-05-16 21:34 UTC, fhomaia approved these changes

2021-05-16 21:39 UTC, fhomaia commented on src/pages/Home.jsx
>              Digite algum termo de Pesquisa ou escolha uma categoria.
o p em pesquisa está maiúsculo, por isso não passou no requisito 2.
```suggestion
            Digite algum termo de pesquisa ou escolha uma categoria.
```

2021-05-16 21:40 UTC, fhomaia requested changes
Alterar a palavra pesquisa na Home page para passar no requisito 2

2021-05-17 16:08 UTC, fhomaia approved these changes

2021-05-17 16:08 UTC, merged