REQUEST 10 V3
tryber/sd-010-b-project-frontend-online-store pull request #424
Opened 2021-05-20 16:52 UTC by denis-rossati

O clickCart do itemDetails foi atualizado e tentei implementar a 9 também, mas continua assíncrona e utilizando o "getItemById". no componentDidMount

2021-05-20 21:45 UTC, andredebem commented on src/pages/ShoppingCart.jsx
> +    // Antes o 04 nçai adi
não entendi muito bem esse comentário...

2021-05-20 21:47 UTC, andredebem requested changes

2021-05-20 21:47 UTC, andredebem commented on src/pages/ShoppingCart.jsx
> +    // Antes o 04 nçai adi
Não entendi muito bem esse comentário... Poderia dar uma olhadinha?

2021-05-21 16:43 UTC, denis-rossati commented on src/pages/ShoppingCart.jsx
> +    // Antes o 04 nçai adi
Também não entendi, apaguei esse trem kkkkkkk

2021-05-25 16:53 UTC, eraldoalmeida approved these changes

2021-05-26 13:40 UTC, merged