[Equipe 6] [Requisito 3]
tryber/sd-010-b-project-frontend-online-store pull request #71
Opened 2021-05-14 20:33 UTC by lucasrb04

Adicionar uma pagina de carrinho de compras e o botão na home

2021-05-14 22:00 UTC, Renan0211 requested changes
No geral tá ótimo, só talvez alterar a renderização do componente para uma renderização condicional como eu comentei lá 😄

2021-05-14 22:05 UTC, lucasrb04 commented on src/pages/Checkout.jsx
> +    );
Maravilha, aí já deixa pronto pra proxima parte né? vou fazer isso, resolver o conflito e dou outro push!! Valeuu

2021-05-16 14:16 UTC, CamilaCode7 approved these changes

2021-05-17 17:26 UTC, legalvao1 approved these changes

2021-05-17 18:03 UTC, Renan0211 approved these changes

2021-05-17 18:03 UTC, JanderLiborio20 approved these changes

2021-05-17 18:04 UTC, merged